USE example;

CREATE TABLE ORDENDISENIO(
    RESPONSABLE_CEDULA CHAR(10) NOT NULL,
    PRODUCTO VARCHAR(100) PRIMARY KEY UNIQUE,
    CAMPANIA VARCHAR(100) NOT NULL,
    MARCA CHAR(30) NOT NULL,
    ESTADO INT NOT NULL, -- 1=APROBADA  2=DESAPROBADA
    Foreign Key (RESPONSABLE_CEDULA) REFERENCES PERSONAS(CEDULA)
);

CREATE TABLE REGISTROS(
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    DISENIADOR CHAR(10) NOT NULL,
    HORA_INICIO DATETIME NOT NULL,
    HORA_FINAL DATETIME NOT NULL,
    OBSERVACIONES VARCHAR(255)
);
