DROP DATABASE IF EXISTS javierDiez;
CREATE DATABASE javierDiez;
USE javierDiez;

CREATE TABLE personas (
    cedula VARCHAR(255) PRIMARY KEY,
    per_nombres VARCHAR(255) NOT NULL,
    per_apellidos VARCHAR(255) NOT NULL,
    per_fechaNacimiento DATE NOT NULL,
    per_estado BOOLEAN,
    per_areaTrabajo VARCHAR(255) NOT NULL,
    per_correo
);

CREATE TABLE usuarios (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
);



CREATE TABLE orden_disenio(
    od_id INT UNSIGNED UNIQUE AUTO_INCREMENT NOT NULL,
    od_responsable VARCHAR(255) NOT NULL,  --cedula
    od_producto VARCHAR(255) PRIMARY KEY,
    od_marca VARCHAR(255) NOT NULL,
    od_fechaEntrega DATETIME NOT NULL,
    od_estado ENUM("PROPUESTA", "DESAPROBADA", "MATERIALIDAD", "OP") NOT NULL, 
    Foreign Key (RESPONSABLE_CEDULA) REFERENCES PERSONAS(CEDULA)
);

CREATE TABLE REGISTROS(
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    PRODUCTO VARCHAR(100) NOT NULL,
    DISENIADOR CHAR(10) NOT NULL,
    HORA_INICIO DATETIME NOT NULL,
    HORA_FINAL DATETIME,
    OBSERVACIONES VARCHAR(255),
    Foreign Key (PRODUCTO) REFERENCES ORDENDISENIO(PRODUCTO)
);


